### ISSUE TITLE
Network Tag Loader node unusable after recent updates

### ISSUE THREAD

**Issue by drphero** [CosmicLaca/ComfyUI_Primere_Nodes#10]
After updating the nodes today, the Network Tag Loader node gives the following error. I'm not sure which commit this started in but as of commit bcb099f it was still working.

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\Shadow\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\Shadow\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\Shadow\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\Shadow\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\Nodes\Dashboard.py", line 1243, in load_networks
    lora_name = utility.get_closest_element(NetworkName, LoraList)
  File "C:\Users\Shadow\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\components\utility.py", line 319, in get_closest_element
    cutoff_list = list(np.around(np.arange(0.1, 1.05, 0.05).tolist(), 2))[::-1]
TypeError: 'list' object is not callable
```

**Comment by CosmicLaca** [comment]
@drphero Thank you! I rethinked the "closest elements" logic, and this function used wrong variable name. Modified, but not tested yet :)

**Comment by drphero** [comment]
Just pulled the latest changes and it looks like it's working again and producing identical results to manually loading the loras.
