### ISSUE TITLE
Can't install (again)

### ISSUE THREAD

**Issue by Ainaemaet** [CosmicLaca/ComfyUI_Primere_Nodes#20]
Hello, while previously I had the ultralytics issue (had to install manually) and got it to work:  with the new version on a fresh install everything seems to go well at first, but after rebooting the comfyui server and a refresh, I get: 

Traceback (most recent call last):
  File "/home/myname/ml/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myname/ml/ComfyUI/custom_nodes/ComfyUI_Primere_Nodes/__init__.py", line 7, in <module>
    from .Nodes import Dashboard
  File "/home/myname/ml/ComfyUI/custom_nodes/ComfyUI_Primere_Nodes/Nodes/Dashboard.py", line 20, in <module>
    from ..components import clipping
  File "/home/myname/ml/ComfyUI/custom_nodes/ComfyUI_Primere_Nodes/components/clipping.py", line 2, in <module>
    from .long_clip_model import longclip
ModuleNotFoundError: No module named 'ComfyUI_Primere_Nodes.components.long_clip_model'

Cannot import /home/myname/ml/ComfyUI/custom_nodes/ComfyUI_Primere_Nodes module for custom nodes: No module named 'ComfyUI_Primere_Nodes.components.long_clip_model'

and when I try to load any of the primere workflows, _every_ node is red except for the basic image previews, VAE decodes, etc (the regular included ComfyUI nodes).

I've tried every combination of installing things that I can, I've gone to custom_nodes/ComfyUI_Primere_Nodes folder and ran pip install -r requirements.txt (no errors there), and been at this for hours - but I'm not a python expert by any means and don't know what else to do?

**Comment by CosmicLaca** [comment]
@Ainaemaet oooooo sorry i forgot to push new required lib yesterday. Problem will be solved soon today. The new files for new clipping completly missing from git. The clip encoder changed

**Comment by CosmicLaca** [comment]
@Ainaemaet Ok I uploaded missing files. Try again pls.
