### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by Neytiri7** [CosmicLaca/ComfyUI_Primere_Nodes#21]
Traceback (most recent call last):
  File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\__init__.py", line 3, in <module>
    from .components import primereserver
  File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\components\primereserver.py", line 3, in <module>
    from ..components import utility
  File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\components\utility.py", line 25, in <module>
    import pytorch_lightning as pl
ModuleNotFoundError: No module named 'pytorch_lightning'

Cannot import O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes module for custom nodes: No module named 'pytorch_lightning'
![noname](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/139053327/2825e368-485b-4662-bea7-241281cadfc3)

**Comment by CosmicLaca** [comment]
@Neytiri7 Hi, just enter `pip install pytorch_lightning` at terminal after activated venv, I forgot to insert pytorch_lightning to the requirements.txt. Will be updated soon.
