### ISSUE TITLE
error come up after update

### ISSUE THREAD

**Issue by 1038lab** [CosmicLaca/ComfyUI_Primere_Nodes#26]
Collecting clip (from -r requirements.txt (line 7))
  Downloading clip-0.2.0.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\nelson\AppData\Local\Temp\pip-install-kaaexbbr\clip_6d33dd565ce943728a93db26e1d40e67\setup.py", line 4, in <module>
          import clip
        File "C:\AI\ComfyUI\python_embeded\Lib\site-packages\clip\__init__.py", line 1, in <module>
          from .clip import *
        File "C:\AI\ComfyUI\python_embeded\Lib\site-packages\clip\clip.py", line 6, in <module>
          from pkg_resources import packaging
      ImportError: cannot import name 'packaging' from 'pkg_resources' (C:\AI\ComfyUI\python_embeded\Lib\site-packages\pkg_resources\__init__.py)
      [end of output]

**Comment by m-ptacek** [comment]
Same here. I found solution to similar problem on https://stackoverflow.com/questions/78604018/ - have to downgrade setuptools to version 69.5.1 (python -m pip install setuptools==69.5.1).

**Comment by CosmicLaca** [comment]
As I see I cant help with coding if setuptools downgrade solve the problem.

**Comment by Mikerhinos** [comment]
Personnally I modified clip.py from the Python package and the long_clip.py from the custom node to change the import from 
from pkg_resources import packaging
to only
import packaging
The long_clip.py change has to be redone at each custon nodes update, but it's fast to do.
