### ISSUE TITLE
Error pop-up after update

### ISSUE THREAD

**Issue by Neytiri7** [CosmicLaca/ComfyUI_Primere_Nodes#39]
Traceback (most recent call last):
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\__init__.py", line 3, in <module>
    from .components import primereserver
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\components\primereserver.py", line 14, in <module>
    from ..Nodes.Inputs import PrimereStyleLoader
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\Nodes\Inputs.py", line 379, in <module>
    class PrimereLLMEnhancer:
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\Nodes\Inputs.py", line 387, in PrimereLLMEnhancer
    allsubdirs = list(os.listdir(Path(model_root)))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Specified path not found: 'W:\\SynologyDrive\\ComfyUI-webui\\ComfyUI\\custom_nodes\\ComfyUI_Primere_Nodes\\Nodes\\Downloads\\LLM'

Cannot import W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes module for custom nodes: [WinError 3] Specified path not found: 'W:\\SynologyDrive\\ComfyUI-webui\\ComfyUI\\custom_nodes\\ComfyUI_Primere_Nodes\\Nodes\\Downloads\\LLM'

**Comment by mbac** [comment]
Can confirm similar error on Ubuntu virtual machine. Fails at `allsubdirs = list(os.listdir(Path(model_root)))`, apparently because there is no `LLM` subdir under `Downloads`.

After creating with `mkdir LLM`, I got an error that the `diffusers` package wasn't installed in the ComfyUI venv. While in the venv, I used `python -m pip install diffusers` to install and Comfy started downloading ultralytics segmentation models (not sure if this is related to this node package, or if it was something from other nodes that wouldn't run because of previous errors at Comfy startup).

No more errors then… Can't presently fully test if nodes are working though.

**Comment by CosmicLaca** [comment]
@mbac Thanks for quick answer. Handled the problem within the code. @Neytiri7 I hope problem solved. The missing `diffusers` module have to install manually if update. @mbac Yes the basic segmentation models downloaded by this nodepack.
